#!/usr/bin/env bash
#
##############################################################################
# Copyright 20015 rcrowther
#
# This is free software; see the distribution for copying conditions.
# There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.
##############################################################################

## Point at a scala installation
# Empty tries for an installed version.
#SCALA_HOME=""

## The name of the executable to create
SCALA_EXECUTABLE="tml"


#!SCALA_HOME.isEmpty 
if [[ -n "$SCALA_HOME" ]]; then
SCALAEXE="$SCALA_HOME/bin/scalac" 
else
SCALAEXE="scalac"
fi

if [[ -n "$JAVA_HOME" ]]; then
JAREXE="$JAVA_HOME/bin/" 
else
JAREXE="jar"
fi

mkdir build
mkdir build/main
mkdir build/main/scala
PWD="$(pwd)"
echo "compiling..."


SRCS="$(find $PWD/src/ | grep scala$)"
#-exec grep \"scala$\" {}
#echo $SCALAEXE -d build/main/scala -toolcp lib/script_0.2.1.jar $SRCS

#scalac @scalacArgs
"$($SCALAEXE -verbose -d build/main/scala $SRCS)"

# Make manifest
echo "Manifest-Version: 1.0
Specification-Title: $SCALA_EXECUTABLE
Main-Class: tml.Runner" > "$PWD/MANIFEST.MF"

# Make .jar
$JAREXE cfm $SCALA_EXECUTABLE.jar MANIFEST.MF -C build/main/scala .

# Remove the now-copied manifest
rm -v MANIFEST.MF

# build the distro package
mkdir $SCALA_EXECUTABLE
mkdir $SCALA_EXECUTABLE/doc
mkdir $SCALA_EXECUTABLE/lib
mkdir $SCALA_EXECUTABLE/bin

# copy the launch script
cp tools/$SCALA_EXECUTABLE $SCALA_EXECUTABLE/bin

# copy the support library jar
#cp -v lib/script* ssc/lib

# move the executing jar
mv -v $SCALA_EXECUTABLE.jar $SCALA_EXECUTABLE/lib



# copy the documentation
cp -v text/README $SCALA_EXECUTABLE/doc
cp -v text/INSTALL $SCALA_EXECUTABLE/doc
cp -v text/LICENSE $SCALA_EXECUTABLE/doc
